Socket.io implementation failed.
Error: Failed to load resource: the server responded with a status of 404 (Not Found)
Suspected to be Gulp or browsersync that is causing the problem.
Confusion level: Over 9000